"""Initial migration

Revision ID: ea6135045564
Revises: 
Create Date: 2024-10-09 19:49:08.100266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea6135045564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('band_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('band_album', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_id'), 'bands', ['id'], unique=False)
    op.create_table('sub_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_genres_id'), 'sub_genres', ['id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_sub_genres_id'), table_name='sub_genres')
    op.drop_table('sub_genres')
    op.drop_index(op.f('ix_bands_id'), table_name='bands')
    op.drop_table('bands')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
